### ISSUE TITLE
node requires >=18, is the requirement too high?

### ISSUE THREAD

**Issue by xujiali111** [lgrammel/ai-utils.js#18]
node requires >=18, is the requirement too high?
I installed it with node 14, and no error was reported when it was developed and used, but an error was reported when I tried to package and deploy.
error ai-utils.js@0.0.25: The engine "node" is incompatible with this module. Expected version ">=18". Got "14.18.0"
error Found incompatible module.

**Comment by lgrammel** [comment]
`ai-utils.js` uses the Node.js fetch API, which was experimental before Node 18. Therefore Node 18 is required (unless you switch on experimental fetch in earlier versions).
